#!/bin/sh

wget ftp://ftp.perforce.com/perforce/r20.1/bin.linux26x86_64/p4d
chmod +x p4d
sudo mv p4d /usr/local/bin
sudo adduser perforce
sudo mkdir /perforce_depot
sudo chown perforce /perforce_depot
sudo mkdir /var/log/perforce
sudo chown perforce /var/log/perforce
sudo apt-get install daemon
cd /etc/init.d
wget https://raw.githubusercontent.com/askeam/gc_run/master/p4ds
chmod +x /etc/init.d/p4ds
sudo update-rc.d p4ds defaults
sudo reboot
